### ISSUE TITLE
扫码和密码现在都无法正常登陆

### ISSUE THREAD

**Issue by fantasy-aster** [kokkorojs/kokkoro-core#1]
之前一直都好好的，现在掉线后不管用那种方式都登录不上，有什么好的解决办法么 QAQ

**Comment by xueelf** [comment]
草，我一直以为这个问题我写文档里了 ~~找了半天发现 README 和文档都没写~~

扫码登录现在只能在 **同一 ip** 下进行，如果你要在服务器登录 bot 只能用密码登录，异地扫码现在是登不上的

密码登录可以 [参考这里](https://github.com/takayama-lily/oicq/wiki/01.使用密码登录-(滑动验证码教程)) ，推荐使用 wiki 中给出的 app 抓取 ticket，tx 修改了算法，要在安卓 **真机环境** 过验证，模拟器或者浏览器 network 里抓现在也是用不了的，登录比以前繁琐了不少

如果过不了验证还有一个方法，在本地扫码挂一段时间，因为异地密码登录都需要过验证，扫码不用，挂一段时间后在换成密码登录，此时登录不会弹出验证，之后将根目录下 `data/bot/{qq}/` 里生成的 token 复制到服务器就能直接登录
