### ISSUE TITLE
编写的本地插件，完全没反应

### ISSUE THREAD

**Issue by guyingd** [kokkorojs/kokkoro-core#2]
![Uploading Screenshot_2022-07-27-20-25-03-180_com.tencent.mobileqq.jpg…]()

**Comment by guyingd** [comment]
![Screenshot_2022-07-27-20-25-03-180_com tencent mobileqq](https://user-images.githubusercontent.com/79262296/181246282-33e6f7a4-464a-4dfe-bd46-975fc88d67d3.jpg)

**Comment by xueelf** [comment]
麻烦提供一下相关代码段及日志哦  
![不中咧](https://vip2.loli.io/2022/07/27/FevBiu6kbo9zUP5.png)
