### ISSUE TITLE
求一个功能，通过http请求给指定人或群发消息，将收到的消息以http请求发送到另外的服务器接口（可配置）

### ISSUE THREAD

**Issue by msyCandy** [kokkorojs/kokkoro-core#7]
### 此功能的开发将会解决什么问题？

http请求使用此bot

### 解决该问题所需的功能点有哪些？

http请求到bot发送消息

**Comment by xueelf** [comment]
kokkoro 没有提供网络请求相关的方法，未来也不会提供，不过你可以直接安装 `axios` 等库实现，这点在文档里没有提及 orz

如果想要根据指令参数发送 http 请求，在 `ctx.query` 里能获取指令相关属性，属性名与 `command` 内的定义保持一致，可以参考下列例子：

```typescript
import axios from 'axios';
import { Plugin } from 'kokkoro';

const service = axios.create({
  baseURL: 'http://localhost:2333/api',
})
const plugin = new Plugin();

plugin
  .command('request <message>')
  .action(async (ctx) => {
    const { message } = ctx.query;
    const response = await service.post('/test', {
      message,
    });
  })
```

目前 `kokkoro.json` 定义了 `port` 字段，但并未使用，后续将会作为 serve 提供 web api 及 admin 等服务，可以关注 [kokkoro web](https://github.com/kokkorojs/web) 这个仓库

**Comment by xueelf** [comment]
已发布 [kokkoro v2.0.0-alpha.8](https://github.com/kokkorojs/kokkoro/releases/tag/v2.0.0-alpha.8) 与 [@kokkoro/web v0.1.3](https://github.com/kokkorojs/web/releases/tag/v0.1.3)，新增 web api 服务及 admin 后台管理，文档可查阅 [API](https://kokkoro.js.org/api) 一栏
