### ISSUE TITLE
增加沙箱环境的切换

### ISSUE THREAD

**Issue by Ember2024** [kokkorojs/kokkoro-core#8]
### 功能描述

在kokkoro.json中增加sandbox配置以便于沙箱和生产环境的切换
```
        "bots": {
            "type": "array",
            "description": "bot 信息，可添加多个",
            "minProperties": 1,
            "items": {
                "properties": {
                    "sandbox" : {
                        "description": "是否处于沙箱场景",
                        "type": "boolean"
                    }
                }
            }
        }
```

**Comment by xueelf** [comment]
`kokkoro@2.0.6` 已添加对沙盒环境的支持，可更新项目依赖后使用。(●'◡'●)

**Comment by Ember2024** [comment]
即使已在kokkoro.json中添加sandbox配置选项,但仍会请求[正式环境api](https://api.sgroup.qq.com/)
应向[沙箱环境api](https://sandbox.api.sgroup.qq.com)发送get请求
配置文件↓
`
{
  "$schema": "https://kokkoro.js.org/schema.json",
  "server": {
    "port": 2333,
    "domain": "http://localhost"
  },
  "log_level": "DEBUG",
  "events": [
    "PUBLIC_GUILD_MESSAGES",
    "GUILD_MESSAGES"
  ],
  "bots": [
    {
      "appid": "***",
      "token": "***",
      "secret": "***",
      "sandbox": true
    }
  ]
}
`
DEBUG日志↓
`
[2024-01-26T20:49:08.115] [DEBUG] [***] - API Request: {
  "url": "/gateway",
  "method": "GET",
  "origin": "https://api.sgroup.qq.com",
  "headers": {
    "Authorization": "***",
    "X-Union-Appid": "***"
  }
}
[2024-01-26T20:49:08.400] [DEBUG] [***] - API Response: {
  "message": "接口访问源IP不在白名单",
  "code": 11298,
  "err_code": 40023002,
  "trace_id": "***"
}
`

**Comment by Ember2024** [comment]
能否通过一下QQ群的加群申请？

**Comment by xueelf** [comment]
> 能否通过一下QQ群的加群申请？

没收到加群申请，可以重新申请一下，还是不行可以搜索 1030982964，这个问题我正在排查 ⊙﹏⊙∥

**Comment by Ember2024** [comment]
好像被QQ屏蔽掉了










Ember
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月26日(周五) 晚上9:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [kokkorojs/kokkoro] 增加沙箱环境的切换 (Issue #8)




  
能否通过一下QQ群的加群申请？
  
没收到加群申请，可以重新申请一下，还是不行可以搜索 1030982964，这个问题我正在排查 ⊙﹏⊙∥

**Comment by Ember2024** [comment]
> > 能否通过一下QQ群的加群申请？
> 
> 没收到加群申请，可以重新申请一下，还是不行可以搜索 1030982964，这个问题我正在排查 ⊙﹏⊙∥

或许是被QQ屏蔽掉了

**Comment by xueelf** [comment]
> > > 能否通过一下QQ群的加群申请？
> > 
> > 
> > 没收到加群申请，可以重新申请一下，还是不行可以搜索 1030982964，这个问题我正在排查 ⊙﹏⊙∥
> 
> 或许是被QQ屏蔽掉了

草，可以加我 Q: 2225151531

**Comment by Ember2024** [comment]
> > > > 能否通过一下QQ群的加群申请？
> > > 
> > > 
> > > 没收到加群申请，可以重新申请一下，还是不行可以搜索 1030982964，这个问题我正在排查 ⊙﹏⊙∥
> > 
> > 
> > 或许是被QQ屏蔽掉了
> 
> 草，可以加我 Q: 2225151531

搜不到，你开搜索了吗(?)

**Comment by xueelf** [comment]
> > > > > 能否通过一下QQ群的加群申请？
> > > > 
> > > > 
> > > > 没收到加群申请，可以重新申请一下，还是不行可以搜索 1030982964，这个问题我正在排查 ⊙﹏⊙∥
> > > 
> > > 
> > > 或许是被QQ屏蔽掉了
> > 
> > 
> > 草，可以加我 Q: 2225151531
> 
> 搜不到，你开搜索了吗(?)

你有问题.jpg(

**Comment by Ember2024** [comment]
18884027

**Comment by Ember2024** [comment]
![image](https://github.com/kokkorojs/kokkoro/assets/131529788/0ba3fb6b-f26f-4407-85cc-129778931481)
